"""empty message

Revision ID: 17c1ea80b2b7
Revises: 2e19637c3fdc
Create Date: 2015-03-22 17:18:41.743957

"""

# revision identifiers, used by Alembic.
revision = '17c1ea80b2b7'
down_revision = '2e19637c3fdc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
