"""empty message

Revision ID: 2e19637c3fdc
Revises: 433d2db3ff19
Create Date: 2015-03-22 12:56:13.241212

"""

# revision identifiers, used by Alembic.
revision = '2e19637c3fdc'
down_revision = '433d2db3ff19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(length=10000), autoincrement=False, nullable=False))
    ### end Alembic commands ###
