"""empty message

Revision ID: 433d2db3ff19
Revises: 10da9a5f6d98
Create Date: 2015-03-21 16:14:31.877464

"""

# revision identifiers, used by Alembic.
revision = '433d2db3ff19'
down_revision = '10da9a5f6d98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
